### ISSUE TITLE
小构思

### ISSUE THREAD

**Issue by ashinnotfound** [ashinnotfound/ChatGPT-YourChatRobot#12]
正在尝试写个页面来方便控制你的GPT

**Comment by ashinnotfound** [comment]
你们有什么需求吗，比如更换GPT模型、重置会话记录什么的

**Comment by wb3368316006** [comment]
> 你们有什么需求吗，比如更换GPT模型、重置会话记录什么的
目前有一个需求，可以加入表情处理吗，机器人识别表情后发送对应的emoij 表情或其他图文。

**Comment by nashor1** [comment]
作者对项目的机器人做了一定的初始化，如果大家不想这个qqbot太笨的话可以把BotUtil.java文件的66-73行注释掉，以及AcconutConfig.java文件的第50行 basicPrompt ，改成basicPrompt = ”“;即可体验最原始的gpt，当然想要你们想要自定义初始化机器人也可以（手动滑稽）

**Comment by ashinnotfound** [comment]
> 作者对项目的机器人做了一定的初始化，如果大家不想这个qqbot太笨的话可以把BotUtil.java文件的66-73行注释掉，以及AcconutConfig.java文件的第50行 basicPrompt ，改成basicPrompt = ”“;即可体验最原始的gpt，当然想要你们想要自定义初始化机器人也可以（手动滑稽）

66-73行那几行是为了防止提问过长，可能我设定的有些保守，你们可以自己改改🤪

**Comment by rhZhang0228** [comment]
感觉调用apiKey的比较拉，基本都不怎么写代码，都是只给一段说明文字

**Comment by nashor1** [comment]
> 感觉调用apiKey的比较拉，基本都不怎么写代码，都是只给一段说明文字

都说让你把初始化代码删掉，非不听。

**Comment by rhZhang0228** [comment]
> > 感觉调用apiKey的比较拉，基本都不是怎么写代码，都是只给一段说明文字
> 
> 都说让你把初始化代码剪掉，非不听。

懂了懂了，才看到

**Comment by rhZhang0228** [comment]
> > 感觉调用apiKey的比较拉，基本都不是怎么写代码，都是只给一段说明文字
> 
> 都说让你把初始化代码剪掉，非不听。

大佬，你可能理解错我的意思了。我的意思是感觉调用apikey版本的chatgpt，基本都不咋写代码。比如说我向机器人提问：“帮我构建一个springboot项目”。机器人只会给出一小段文字描述怎么构建。而当我在网页版的ChatGPT提问时，他会给出如何编写启动类（给我一段启动类的示例），maven依赖具体添加什么等等。这是否是调用api的chatgpt本身和网页版的不一样？

**Comment by nashor1** [comment]
> > > 感觉调用apiKey的比较拉，基本都不是怎么写代码，都是只给一段说明文字
> > 
> > 都说让你把初始化代码剪掉，非不听。
> 
> 大佬，你可能理解错我的意思了。我的意思是感觉调用apikey版本的chatgpt，基本都不咋写代码。比如说我向机器人提问：“帮我构建一个springboot项目”。机器人只会给出一小段文字描述怎么构建。而当我在网页版的ChatGPT提问时，他会给出如何编写启动类（给我一段启动类的示例），maven依赖具体添加什么等等。这是否是调用api的chatgpt本身和网页版的不一样？

gpt官网那边是3.5，apikey调用的是3.0，你可以在api给出文字说明后让他用代码实现
