### ISSUE TITLE
请问怎么run

### ISSUE THREAD

**Issue by ezyzzy** [ashinnotfound/ChatGPT-YourChatRobot#23]

**Comment by ashinnotfound** [comment]
配置好application.yml，启动即可

**Comment by ezyzzy** [comment]
> 配置好application.yml，启动即可

请问意思是执行这个文件吗？
[MyChatGptApplication.java](https://github.com/ashinnotfound/ChatGPT-QQRobot/blob/master/src/main/java/com/ashin/MyChatGptApplication.java)

**Comment by ashinnotfound** [comment]
> > 配置好application.yml，启动即可
> 
> 请问意思是执行这个文件吗？ [MyChatGptApplication.java](https://github.com/ashinnotfound/ChatGPT-QQRobot/blob/master/src/main/java/com/ashin/MyChatGptApplication.java)

对的

**Comment by ezyzzy** [comment]
> > > 配置好application.yml，启动即可
> > 
> > 
> > 请问意思是执行这个文件吗？ [MyChatGptApplication.java](https://github.com/ashinnotfound/ChatGPT-QQRobot/blob/master/src/main/java/com/ashin/MyChatGptApplication.java)
> 
> 对的

不知道是不是我的原因 jdk 19.0.2好像不支持，会报错

**Comment by ashinnotfound** [comment]
> > > > 配置好application.yml，启动即可
> > > 
> > > 
> > > 请问意思是执行这个文件吗？ [MyChatGptApplication.java](https://github.com/ashinnotfound/ChatGPT-QQRobot/blob/master/src/main/java/com/ashin/MyChatGptApplication.java)
> > 
> > 
> > 对的
> 
> 不知道是不是我的原因 jdk 19.0.2好像不支持，会报错

会报什么错误呢，我用的也是19.02，是正常的
