### ISSUE TITLE
An exception occurred when processing event. Subscriber scope: '<unnamed>'. Broadcaster scope: 'Bot.2736705059.EventDispatcher' net.mamoe.mirai.event.ExceptionInEventHandlerException: Exception in EventHandler

### ISSUE THREAD

**Issue by wuhonghui123** [ashinnotfound/ChatGPT-YourChatRobot#27]
An exception occurred when processing event. Subscriber scope: '<unnamed>'. Broadcaster scope: 'Bot.2736705059.EventDispatcher'
net.mamoe.mirai.event.ExceptionInEventHandlerException: Exception in EventHandler

**Comment by ashinnotfound** [comment]
有无更详细的报错信息？

**Comment by nashor1** [comment]
这个问题是你的机器连不上chat的api，也就是说你本地机器或者服务器没代理
