### ISSUE TITLE
本地能登录，但是服务器死活登录不上

### ISSUE THREAD

**Issue by Lukangkang123** [ashinnotfound/ChatGPT-YourChatRobot#29]
本地电脑之前试了几次，不填代理，梯子开全局能登录了。但是远程服务器还是登录不上。报错如下：
Error(bot=Bot(1839294824), code=45, title=禁止登录, message=登录失 败，建议升级最新版本后重试，或通过问题反馈与我们联系。

请问这是本地打包到服务器的正确步骤是什么？是clean->verify->package吗？

**Comment by ashinnotfound** [comment]
对的，是这样打包的。出现这个问题的原因依旧是该死的qq风控问题😵

**Comment by Lukangkang123** [comment]
> 对的，是这样打包的。出现这个问题的原因依旧是该死的qq风控问题😵

换个qq登录方式会不会好些，我用go-cqhttp登录就没事

**Comment by ashinnotfound** [comment]
> > 对的，是这样打包的。出现这个问题的原因依旧是该死的qq风控问题😵
> 
> 换个qq登录方式会不会好些，我用go-cqhttp登录就没事

是有考虑过更换qq登陆方法，但是用java写的除了mirai好像能用的比较少，用其他语言的可能会引起使用的不便，这和我开箱即用的想法有悖，所以我也很烦，我再接着摸索摸索吧。

**Comment by ashinnotfound** [comment]
> > > > 对的，是这样打包的。出现这个问题的原因依旧是该死的qq风控问题😵
> > > 
> > > 
> > > 换个qq登录方式会不会好些，我用go-cqhttp登录就没事
> > 
> > 
> > 是有考虑过更换qq登陆方法，但是用java写的除了mirai好像能用的比较少，用其他语言的可能会引起使用的不便，这和我开箱即用的想法有悖，所以我也很烦，我再接着摸索摸索吧。
> 
> 之前有人说本地qq登录的缓存也打包进服务器了，不知道这样能不能解决

用 #26 docker的方式似乎是可行的

**Comment by nashor1** [comment]
你们的qq都是只能用watch登录方式吗，指定登录方式得改变一下代码，在AccountConfig.java文件的64行里面
![image](https://user-images.githubusercontent.com/115065774/223450087-1d13e18d-933e-4b1d-81d6-b2e90f9eb951.png)
for循环不要用这种方式来遍历登录方式，建议直接传入一个值，跟进去代码里面就能看到有几个登录方式，传列表第三个进去就行了，遍历登录方式的方法如果登录失败会增加qq的风险系数，失败后的频繁操作也很繁琐
![image](https://user-images.githubusercontent.com/115065774/223450690-dea25df0-83f0-4a10-96f6-2410e8c4b200.png)

**Comment by ashinnotfound** [comment]
> 你们的qq都是只能用watch登录方式吗，指定登录方式得改变一下代码，在AccountConfig.java文件的64行里面 ![image](https://user-images.githubusercontent.com/115065774/223450087-1d13e18d-933e-4b1d-81d6-b2e90f9eb951.png) for循环不要用这种方式来遍历登录方式，建议直接传入一个值，跟进去代码里面就能看到有几个登录方式，传列表第三个进去就行了，遍历登录方式的方法如果登录失败会增加qq的风险系数，失败后的频繁操作也很繁琐 ![image](https://user-images.githubusercontent.com/115065774/223450690-dea25df0-83f0-4a10-96f6-2410e8c4b200.png)

有的只能ipad，有的只能macos，唯有多试试了
