### ISSUE TITLE
登录问题

### ISSUE THREAD

**Issue by lmuiotctf** [ashinnotfound/ChatGPT-YourChatRobot#31]
![image](https://user-images.githubusercontent.com/52068443/223454761-c935c639-251a-4026-aa6b-85b87fda00be.png)
目前输入ticket 之后没有反应

**Comment by lmuiotctf** [comment]
![image](https://user-images.githubusercontent.com/52068443/223459266-10d0f503-56f4-42ba-be26-0e9ffc24edd2.png)
目前是版本低，这个怎么解决

**Comment by ashinnotfound** [comment]
抱歉未能及时回复，因时间过长，现关闭此issue，如果问题仍然存在，请再次提issue
