### ISSUE TITLE
This model's maximum context length is 4097 tokens. However, you requested 4307 tokens (2259 in the messages, 2048 in the completion). Please reduce the length of the messages or completion. 	at com.theokanning.openai.service.OpenAiService.execute(OpenAiService.java:227)

### ISSUE THREAD

**Issue by 1441853031** [ashinnotfound/ChatGPT-YourChatRobot#42]
This model's maximum context length is 4097 tokens. However, you requested 4307 tokens (2259 in the messages, 2048 in the completion). Please reduce the length of the messages or completion.
	at com.theokanning.openai.service.OpenAiService.execute(OpenAiService.java:227)

**Comment by ashinnotfound** [comment]
你用的是最新版本吗，我今天下午对这个问题进行了更新，应该不会出现这个问题了

**Comment by 1441853031** [comment]
好的
我改一下

**Comment by 1441853031** [comment]
更新后有时候还是会报错

**Comment by 1441853031** [comment]
> 你用的是最新版本吗，我今天下午对这个问题进行了更新，应该不会出现这个问题了

更新后有时候还是会报这个错

**Comment by 1441853031** [comment]
> 你用的是最新版本吗，我今天下午对这个问题进行了更新，应该不会出现这个问题了

遇到点问题，能加一下联系方式吗

**Comment by 1441853031** [comment]
> 
![image](https://user-images.githubusercontent.com/63350299/226783157-bf6e35c6-9be6-4dcd-8974-ea10eee33f28.png)
这个异常好像捕获不到

**Comment by 1441853031** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/63350299/226783157-bf6e35c6-9be6-4dcd-8974-ea10eee33f28.png) 这个异常好像捕获不到

catch (OpenAiHttpException e){
            BotUtil.deleteFirstPrompt(chatBO.getSessionId());
            return chat(chatBO);
        }
改成这样就可以了，谢谢大佬的代码

**Comment by ashinnotfound** [comment]
> > > 
> > 
> > ![image](https://user-images.githubusercontent.com/63350299/226783157-bf6e35c6-9be6-4dcd-8974-ea10eee33f28.png) 这个异常好像捕获不到
> 
> catch (OpenAiHttpException e){
>             BotUtil.deleteFirstPrompt(chatBO.getSessionId());
>             return chat(chatBO);
>         }
> 改成这样就可以了，谢谢大佬的代码

感谢，我待会测试下
