### ISSUE TITLE
如果一堆key里有一个被封禁

### ISSUE THREAD

**Issue by 1441853031** [ashinnotfound/ChatGPT-YourChatRobot#43]
This key is associated with a deactivated account. If you feel this is an error, contact us through our help center at help.openai.com.

提示这个信息，怎么找到这个key

**Comment by ashinnotfound** [comment]
好像只能一个一个试🫠🫠🫠

**Comment by ashinnotfound** [comment]
可以去openai官网，有个地方可以直接输入你的apikey调用模型，你可以去那试试哪个不能用
