### ISSUE TITLE
如果是在服务器运行的话，这个怎么配置

### ISSUE THREAD

**Issue by 1441853031** [ashinnotfound/ChatGPT-YourChatRobot#46]
proxy:
  #  代理配置
  #  国内墙了gpt的api，所以得用代理，一般你使用的代理软件会有相关信息，例子：
  #  host: 127.0.0.1
  #  port: 7890
  #  若不需要留空即可
  host: 127.0.0.1
  port: 7890
这个应该怎么配置

**Comment by ashinnotfound** [comment]
linux里面也装个代理软件，比如[clash-for-linux](https://github.com/wanhebin/clash-for-linux)

**Comment by 1441853031** [comment]
> 

我用的美国服务器，不需要代理，怎么关闭

**Comment by ashinnotfound** [comment]
那留空即可

**Comment by 1441853031** [comment]
留空
提示这个错误Failed to connect to api.openai.com/2001:0:0:0:0:0:4a75:b287:443

**Comment by 1441853031** [comment]
> 留空 提示这个错误Failed to connect to api.openai.com/2001:0:0:0:0:0:4a75:b287:443

java.net.ConnectException: Failed to connect to api.openai.com/2001:0:0:0:0:0:1f0d:490c:443

**Comment by ashinnotfound** [comment]
> > 留空 提示这个错误Failed to connect to api.openai.com/2001:0:0:0:0:0:4a75:b287:443
> 
> java.net.ConnectException: Failed to connect to api.openai.com/2001:0:0:0:0:0:1f0d:490c:443

你试试curl api.openai.com能不能正常连通

**Comment by 1441853031** [comment]
> 



> 

![image](https://user-images.githubusercontent.com/63350299/227130198-f424925d-8ba2-4ace-8ae4-970190462769.png)

**Comment by 1441853031** [comment]
是我服务器的问题呜呜呜呜

**Comment by ashinnotfound** [comment]
> 是我服务器的问题呜呜呜呜

🫣
