### ISSUE TITLE
回复“提问过于频繁(openai限制接口为20prompt/60s)，过一会再来问我吧”

### ISSUE THREAD

**Issue by 123444-7** [ashinnotfound/ChatGPT-YourChatRobot#48]
是因为密钥出错了吗？

**Comment by ashinnotfound** [comment]
> 是因为密钥出错了吗？

就是字面意思

**Comment by 123444-7** [comment]
> > 是因为密钥出错了吗？
> 
> 就是字面意思

但是我一句话都没问，我第一句发“你好”，他就弹这个报错

**Comment by 123444-7** [comment]
> > > > 是因为密钥出错了吗？
> > > 
> > > 
> > > 就是字面意思
> > 
> > 
> > 但是我一句话都没问，我第一句发“你好”，他就弹这个报错
> 
> 这几天chatgpt崩了，网页版也很不稳定，可能是这个原因🤔

api连接的是4吗？如果是3.5能升级到4吗怡雯😁

**Comment by 123444-7** [comment]
> > > > 是因为密钥出错了吗？
> > > 
> > > 
> > > 就是字面意思
> > 
> > 
> > 但是我一句话都没问，我第一句发“你好”，他就弹这个报错
> 
> 这几天chatgpt崩了，网页版也很不稳定，可能是这个原因🤔

2023-03-24 21:29:27.264 ERROR 9028 --- [       Thread-3] c.a.service.impl.InteractServiceImpl     : 向gpt提问失败，提问内容：你好，
原因：You exceeded your current quota, please check your plan and billing details.

后台是这样的

**Comment by ashinnotfound** [comment]
> > > > > 是因为密钥出错了吗？
> > > > 
> > > > 
> > > > 就是字面意思
> > > 
> > > 
> > > 但是我一句话都没问，我第一句发“你好”，他就弹这个报错
> > 
> > 这几天chatgpt崩了，网页版也很不稳定，可能是这个原因🤔
> 
> 2023-03-24 21:29:27.264 ERROR 9028 --- [       Thread-3] c.a.service.impl.InteractServiceImpl     : 向gpt提问失败，提问内容：你好，
> 原因：You exceeded your current quota, please check your plan and billing details.
> 
> 后台是这样的

噢那就是你的账号余额用光了
