### ISSUE TITLE
后台运行

### ISSUE THREAD

**Issue by seagullz4** [ashinnotfound/ChatGPT-YourChatRobot#49]
挂在服务器正常使用，但是不能后台运行，也就是和服务器断开联系时就不能正常使用了

**Comment by seagullz4** [comment]
如何才能后台运行呢？

**Comment by ashinnotfound** [comment]
nohup java -jar 包名 &

**Comment by seagullz4** [comment]
> nohup java -jar 包名 &

你这个不行，我试过，但我问了chatgpt有另外一个办法

1. 输入 "screen" 命令，创建一个新的虚拟终端。
2. 在虚拟终端中输入运行程序的命令，例如 "java -jar ChatGPT-YourChatRobot-3.5.jar"。
3. 按下 "Ctrl + A"，然后按下 "d"，将虚拟终端分离并将其保持在后台运行。

这样的确可以使其后台运行

**Comment by ashinnotfound** [comment]
> > nohup java -jar 包名 &
> 
> 你这个不行，我试过，但我问了chatgpt有另外一个办法
> 
> 1. 输入 "screen" 命令，创建一个新的虚拟终端。
> 2. 在虚拟终端中输入运行程序的命令，例如 "java -jar ChatGPT-YourChatRobot-3.5.jar"。
> 3. 按下 "Ctrl + A"，然后按下 "d"，将虚拟终端分离并将其保持在后台运行。
> 
> 这样的确可以使其后台运行
> 

nohup退出时用exit指令，别直接退终端
