### ISSUE TITLE
itchat4j是改了什么吗

### ISSUE THREAD

**Issue by xjt1995** [ashinnotfound/ChatGPT-YourChatRobot#50]
itchat4j是改了什么吗，用itchat4j-uos源码打包就不能用

**Comment by ashinnotfound** [comment]
[wxmbaci/itchat4j-uos](https://github.com/wxmbaci/itchat4j-uos)源码打包我之前试过是能正常用的(至少3.19是可以的)，现在这个项目用的itchat4j-uos包我只更新了它的pom依赖

**Comment by xjt1995** [comment]
我把okhttp版本升了一下 然后注释了System.setProperty("jsse.enableSNIExtension", "false");  就好了

**Comment by xjt1995** [comment]
好的 感谢指导
