### ISSUE TITLE
Proxy配置问题

### ISSUE THREAD

**Issue by eada123** [ashinnotfound/ChatGPT-YourChatRobot#51]
我自己租了个VPS搭了Trojan，项目我想起在本地PC上，Proxy那里只配置VPS的IP和端口的话是不是没办法连过去？
VPS上面是否还需要做其他的什么配置啊？

**Comment by ashinnotfound** [comment]
你vps的端口防火墙开了吗

**Comment by eada123** [comment]
> 你vps的端口防火墙开了吗

开了的

**Comment by ashinnotfound** [comment]
> > 你vps的端口防火墙开了吗
> 
> 开了的

这就触及到我的知识盲区了🫠🫠

**Comment by eada123** [comment]
> > > 你vps的端口防火墙开了吗
> > 
> > 
> > 开了的
> 
> 这就触及到我的知识盲区了🫠🫠

我的意思是 防火墙是放开了对应端口的，还需要配置其他的吗？

**Comment by ashinnotfound** [comment]
> > > > 你vps的端口防火墙开了吗
> > > 
> > > 
> > > 开了的
> > 
> > 这就触及到我的知识盲区了🫠🫠
> 
> 我的意思是 防火墙是放开了对应端口的，还需要配置其他的吗？

这我不清楚，我只知道proxy那里要配置一个能提供代理作用的ip和端口即可
