### ISSUE TITLE
提示QQ版本过低

### ISSUE THREAD

**Issue by suhm2023** [ashinnotfound/ChatGPT-YourChatRobot#59]
Network selector received exception, closing bot. (net.mamoe.mirai.internal.network.components.LoginFailedExceptionAsNetworkException: Error(bot=Bot(), code=45, title=禁止登录, message=你当前使用的QQ版本过低，请前往QQ官网im.qq.com下载最新版QQ后重试。, errorInfo=))

**Comment by ashinnotfound** [comment]
经典腾讯风控，换网络或者qq号试试😢

**Comment by ashinnotfound** [comment]
尝试了一下 可以先把代理关了 qq登录成功获取缓存cache之后再开代理启动项目
