### ISSUE TITLE
登陆方式为 MACOS ，原因：no standard input for captcha

### ISSUE THREAD

**Issue by fuleigang** [ashinnotfound/ChatGPT-YourChatRobot#60]
外网启动服务的时候报，登陆方式为 MACOS ，原因：no standard input for captcha

**Comment by ashinnotfound** [comment]
滑动验证码的原因？https://github.com/ashinnotfound/ChatGPT-YourChatRobot#%E4%BD%A0%E5%8F%AF%E8%83%BD%E9%9C%80%E8%A6%81%E4%BA%86%E8%A7%A3
