### ISSUE TITLE
com.theokanning.openai.OpenAiHttpException: This is not a chat model and thus not supported in the v1/chat/completions endpoint. Did you mean to use v1/completions?

### ISSUE THREAD

**Issue by cuikunyu123** [ashinnotfound/ChatGPT-YourChatRobot#63]
这是什么错

**Comment by ashinnotfound** [comment]
openai的gpt3.5及以上版本使用chat的completion，此项目默认也使用chat的completion接口，因此如果你使用不是3.5(或以上)的模型，就会报这个错误。你只需把我调completion的接口改为普通的即可

![image](https://user-images.githubusercontent.com/109566763/236688684-828fc33d-063c-487f-bd7a-4da0ed940823.png)
 
具体看https://platform.openai.com/docs/models/model-endpoint-compatibility
