### ISSUE TITLE
访问gpt后响应429， 我的key是刚获取的

### ISSUE THREAD

**Issue by FeifaNiCheng** [ashinnotfound/ChatGPT-YourChatRobot#78]
<img width="1194" alt="image" src="https://github.com/ashinnotfound/ChatGPT-YourChatRobot/assets/52599928/8df18be5-9ea1-4b79-8110-fa901a2d3dd0">

**Comment by FeifaNiCheng** [comment]
<img width="852" alt="image" src="https://github.com/ashinnotfound/ChatGPT-YourChatRobot/assets/52599928/95e8cb9a-e8ad-4038-8014-6d8932571559">

**Comment by ashinnotfound** [comment]
查询下账户余额，刚获取的也不一定是余额充足的
