### ISSUE TITLE
DALL·E 3模型问题 

### ISSUE THREAD

**Issue by X-system** [ashinnotfound/ChatGPT-YourChatRobot#79]
生成出来的图片看起来不像是DALLE3的模型生成出来的，找了一圈不知道在哪里改画图模型，需要在哪里修改呢？

**Comment by ashinnotfound** [comment]
是的 现在默认是2 后续会默认设置为3
你可以先将pom文件com.theokanning.openai-gpt3-java依赖升级为[0.17.0](https://github.com/TheoKanning/openai-java/releases/tag/0.17.0)(或以上), 这个版本[支持了指定dell模型](https://github.com/TheoKanning/openai-java/pull/393/files)
然后就可以在ChatServiceImpl里指定模型
![image](https://github.com/ashinnotfound/ChatGPT-YourChatRobot/assets/109566763/ecbbec47-ab68-4525-912c-03d3bcb2ff4d)

**Comment by X-system** [comment]
牛逼，成功了，画质直接舒服了，微信只能通过链接的方式展示图片吗，有没有能直接展示的方法呢

**Comment by X-system** [comment]
> 是的 现在默认是2 后续会默认设置为3 你可以先将pom文件com.theokanning.openai-gpt3-java依赖升级为[0.17.0](https://github.com/TheoKanning/openai-java/releases/tag/0.17.0)(或以上), 这个版本[支持了指定dell模型](https://github.com/TheoKanning/openai-java/pull/393/files) 然后就可以在ChatServiceImpl里指定模型 ![image](https://user-images.githubusercontent.com/109566763/284561140-ecbbec47-ab68-4525-912c-03d3bcb2ff4d.png)

牛逼，成功了，画质直接舒服了，微信只能通过链接的方式展示图片吗，有没有能直接展示的方法呢

**Comment by ashinnotfound** [comment]
> > 是的 现在默认是2 后续会默认设置为3 你可以先将pom文件com.theokanning.openai-gpt3-java依赖升级为[0.17.0](https://github.com/TheoKanning/openai-java/releases/tag/0.17.0)(或以上), 这个版本[支持了指定dell模型](https://github.com/TheoKanning/openai-java/pull/393/files) 然后就可以在ChatServiceImpl里指定模型 ![image](https://user-images.githubusercontent.com/109566763/284561140-ecbbec47-ab68-4525-912c-03d3bcb2ff4d.png)
> 
> 牛逼，成功了，画质直接舒服了，微信只能通过链接的方式展示图片吗，有没有能直接展示的方法呢

对的 微信现在只能发链接 因为现在用的微信的包年久失修了 发图片相关的api有bug
