### ISSUE TITLE
微信群GPT回复时： “@提问人” 可以实现吗

### ISSUE THREAD

**Issue by X-system** [ashinnotfound/ChatGPT-YourChatRobot#81]
在多人群的情况下，如果好几个人同时提问，GPT回复的场面比较混乱...，能实现在回复问题前@提问人吗，
比如：
123同时提问，GPT回复时 
@1 xxxx  
@2 xxxxx  
@3 xxxxx

而不是：
xxxxx
xxxxxx
xxxxx

**Comment by ashinnotfound** [comment]
还是之前说的微信的sdk包年久失修的问题，支持不了
